import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, Play, MapPinned } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AppShell, SectionHeading, QualityNote } from '@/components/AppShell';
import { GisMap } from '@/components/GisMap';
import { Kpis, TrendChart, IndicatorPanels } from '@/components/Analytics';
import { useDemo } from '@/components/DemoContext';
export const Route = createFileRoute('/dashboard')({head:()=>({meta:[{title:'Watershed Intelligence Dashboard — JalDrishti AI'},{name:'description',content:'Explore demo watershed evidence, geospatial indicators and intervention monitoring.'},{property:'og:title',content:'Watershed Intelligence Dashboard — JalDrishti AI'},{property:'og:description',content:'Map-first watershed monitoring and spatial intelligence prototype.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Dashboard});
function Dashboard() {const {watershed,setGuidedStep}=useDemo();return <AppShell title="Watershed Intelligence Dashboard" subtitle="An integrated view of field evidence, satellite indicators and observed spatial change."><Kpis/><div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_280px] gap-4"><div className="min-w-0"><div className="panel overflow-hidden"><div className="p-4 flex flex-wrap items-center justify-between gap-3"><SectionHeading title="Geospatial Watershed View" caption={`${watershed.name} · Boundary, interventions and geo-coded evidence`}/><Button variant="outline" size="sm" asChild><Link to="/explorer"><MapPinned/> Open Explorer</Link></Button></div><GisMap height="h-[510px]"/></div><div className="grid sm:grid-cols-2 gap-4 mt-4"><div className="panel p-4"><SectionHeading title="Vegetation Indicator" caption="NDVI · observed temporal trend" action={<span className="text-success font-extrabold text-sm">+{watershed.vegetation}%</span>}/><TrendChart kind="ndvi" height={170}/></div><div className="panel p-4"><SectionHeading title="Water Area Indicator" caption="Surface water · illustrative comparison" action={<span className="text-water font-extrabold text-sm">+{watershed.water}%</span>}/><TrendChart kind="water" height={170}/></div></div></div><div className="min-w-0"><IndicatorPanels/><div className="panel p-4 mt-3 bg-primary text-primary-foreground border-primary"><p className="text-[10px] font-extrabold tracking-widest opacity-70">PRESENTATION MODE</p><h3 className="font-extrabold mt-2">Follow the evidence trail</h3><p className="text-xs opacity-80 mt-2 leading-relaxed">From watershed location and field photographs to observed indicators and an assessment report.</p><Button variant="secondary" size="sm" className="mt-4 w-full" onClick={()=>setGuidedStep(0)}><Play/> Launch Guided Demo <ArrowRight/></Button></div></div></div><div className="mt-5"><QualityNote/></div></AppShell>}
