import {createFileRoute,Link} from '@tanstack/react-router';
import {ArrowRight,MapPinned} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {AppShell,SectionHeading} from '@/components/AppShell';
import {GisMap} from '@/components/GisMap';
import {useDemo} from '@/components/DemoContext';
import {watersheds} from '@/data';
export const Route=createFileRoute('/explorer')({head:()=>({meta:[{title:'Watershed Explorer — JalDrishti AI'},{name:'description',content:'Explore demo watershed boundaries, interventions and spatial context.'},{property:'og:title',content:'Watershed Explorer — JalDrishti AI'},{property:'og:description',content:'Explore watershed boundaries and field evidence on a GIS map.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Explorer});
function Explorer(){const {watershed,setWatershedId}=useDemo();return <AppShell title="Watershed Explorer" subtitle="Browse catchments, mapped boundaries and intervention evidence in the demo region."><div className="grid lg:grid-cols-[250px_minmax(0,1fr)] gap-4"><div className="panel p-4"><SectionHeading title="Demo Watersheds" caption="Bhadradri Kothagudem · Telangana"/><div className="space-y-2">{watersheds.map(w=><Button key={w.id} variant={watershed.id===w.id?'secondary':'ghost'} onClick={()=>setWatershedId(w.id)} className="!h-auto w-full !justify-start text-left py-3"><span className="size-8 bg-success-soft text-primary rounded-sm shrink-0 grid place-items-center"><MapPinned className="size-4"/></span><span className="min-w-0"><span className="block font-extrabold text-xs">{w.id} · {w.name}</span><span className="block font-normal text-[10px] text-muted-foreground">{w.area.toLocaleString()} ha · {w.images} images</span></span></Button>)}</div><p className="text-[11px] text-muted-foreground mt-5 border-t border-border pt-4">Boundaries are illustrative shapes centered in the demo region, not official watershed polygons.</p></div><div className="panel overflow-hidden"><div className="p-4"><SectionHeading title={`${watershed.id} · ${watershed.name}`} caption="Interactive watershed context · select a marker for intervention evidence"/></div><GisMap height="h-[540px]"/></div></div><div className="panel p-5 mt-4"><SectionHeading title="Watershed Profile" caption="Illustrative summary for the selected catchment" action={<Button asChild size="sm"><Link to="/interventions" search={{item:undefined}}>View Watershed Profile <ArrowRight/></Link></Button>}/><div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-5">{[['Area',`${watershed.area.toLocaleString()} ha`],['Drainage density','1.6 km/km²'],['Water bodies','14 mapped'],['Interventions',`${watershed.interventions.length*7+2} monitored`],['Geo-coded images',`${watershed.images}`],['Vegetation indicator',`+${watershed.vegetation}%`],['Water indicator',`+${watershed.water}%`],['Change zones',`${watershed.zones} detected`],['Boundary','Illustrative'],['Data status','Demo dataset']].map(([a,b])=><div key={a}><p className="section-label">{a}</p><p className="font-extrabold text-sm mt-1">{b}</p></div>)}</div></div></AppShell>}
