/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangeRouteImport } from './routes/change'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as GeoImagesRouteImport } from './routes/geo-images'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SatelliteRouteImport } from './routes/satellite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRoute = ChangeRouteImport.update({
  id: '/change',
  path: '/change',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoImagesRoute = GeoImagesRouteImport.update({
  id: '/geo-images',
  path: '/geo-images',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change': typeof ChangeRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/geo-images': typeof GeoImagesRoute
  '/login': typeof LoginRoute
  '/satellite': typeof SatelliteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change': typeof ChangeRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/geo-images': typeof GeoImagesRoute
  '/login': typeof LoginRoute
  '/satellite': typeof SatelliteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change': typeof ChangeRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/geo-images': typeof GeoImagesRoute
  '/login': typeof LoginRoute
  '/satellite': typeof SatelliteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change'
    | '/dashboard'
    | '/explorer'
    | '/geo-images'
    | '/login'
    | '/satellite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change'
    | '/dashboard'
    | '/explorer'
    | '/geo-images'
    | '/login'
    | '/satellite'
  id:
    | '__root__'
    | '/'
    | '/change'
    | '/dashboard'
    | '/explorer'
    | '/geo-images'
    | '/login'
    | '/satellite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeRoute: typeof ChangeRoute
  DashboardRoute: typeof DashboardRoute
  ExplorerRoute: typeof ExplorerRoute
  GeoImagesRoute: typeof GeoImagesRoute
  LoginRoute: typeof LoginRoute
  SatelliteRoute: typeof SatelliteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change': {
      id: '/change'
      path: '/change'
      fullPath: '/change'
      preLoaderRoute: typeof ChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-images': {
      id: '/geo-images'
      path: '/geo-images'
      fullPath: '/geo-images'
      preLoaderRoute: typeof GeoImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeRoute: ChangeRoute,
  DashboardRoute: DashboardRoute,
  ExplorerRoute: ExplorerRoute,
  GeoImagesRoute: GeoImagesRoute,
  LoginRoute: LoginRoute,
  SatelliteRoute: SatelliteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
